# Generated by Django 4.1.7 on 2023-03-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[(0, 'Uncompleted'), (1, 'Completed')], max_length=1),
        ),
    ]
